site_name: Tide Wiki
site_description: Wiki and documentation for the Tide mod
site_author: Lightning-64

nav:
  - Home: index.md
  - Mechanics:
    - Fishing Minigame: mechanics/fishing-minigame.md
    - The Bait System: mechanics/bait-system.md
    - Fishing Journal: mechanics/fishing-journal.md
    - Fishing Rod Customization: mechanics/rod-customization.md
  - Items:
    - Fishing Rods: items/fishing-rods.md
    - Fishing Journal: items/fishing-journal.md
    - Angling Table: items/angling-table.md
    - Fishing Bobbers: items/bobbers.md
    - Fishing Hooks: items/hooks.md
    - Fishing Lines: items/lines.md
    - Bait Items: items/bait-items.md
    - Loot Crates: items/loot-crates.md
    - Jelly Torch: items/jelly-torch.md
    - Deep Aqua Crystal/Arrow: items/deep-aqua-crystal-arrows.md
    - Junk Items: items/junk.md
  - Configuration:
    - Mod Config Settings: config/mod-config.md
    - Datapack Guides:
      - Modifying the Journal: config/datapacks/journal-modification.md
      - Custom Bait Items: config/datapacks/custom-bait-items.md
      - Custom Rod Accessories: config/datapacks/custom-rod-accessories.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/773R6cruH6

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Lightning-64/Tide
repo_name: Lightning-64/Tide

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    - scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  logo: assets/tide-white.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy